# Generated by Django 6.0.3 on 2026-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_id_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='company_id',
            field=models.CharField(default='000000000', max_length=10),
        ),
    ]
