# Generated by Django 6.0.3 on 2026-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subscriber_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='company_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
