# Generated by Django 6.0.3 on 2026-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscriber_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='company_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
