# Generated by Django 6.0.3 on 2026-03-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0003_alter_sale_manager_alter_sale_subscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('START', 'Start'), ('END', 'End'), ('POS', 'POS Statement')], max_length=15)),
                ('origin', models.CharField(choices=[('INCOME', 'Income'), ('COST', 'Cost'), ('SALARY', 'Salary'), ('BONUS', 'Bonus'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('BALANCE', 'Balance')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS'), ('ONLINE', 'Online'), ('SUBSCRIPTION', 'Subscription'), ('PREPAID', 'Prepaid'), ('BANK', 'Bank')], max_length=15)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.calendarevent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.employee')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.sale')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('type__in', ['POS', 'START', 'END'])), fields=('date', 'type'), name='unique_pos_start_end_per_date')],
            },
        ),
    ]
