# Generated by Django 6.0.3 on 2026-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
