# Generated by Django 6.0.3 on 2026-04-01 17:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0003_alter_sale_manager_alter_sale_subscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('type', models.CharField(choices=[('BONUS', 'Bonus'), ('SALARY', 'Salary'), ('PENALTY', 'Penalty')], default='SALARY', max_length=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='core.calendarevent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='core.employee')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='sales.sale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('date', 'employee', 'type', 'sale')},
            },
        ),
    ]
