# Generated by Django 6.0.3 on 2026-03-20 09:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial')], default='UNPAID', max_length=10)),
                ('reg_number', models.CharField(max_length=15)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.calendarevent')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_sales', to='core.employee')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.subscriber')),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiclebrand')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_sales', to='core.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('services', models.ManyToManyField(blank=True, related_name='carts', to='core.service')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
