# Generated by Django 6.0.3 on 2026-03-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='core.serviceprice')),
            ],
            options={
                'unique_together': {('cart', 'service')},
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='services',
        ),
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='carts', through='sales.CartItem', to='core.service'),
        ),
    ]
