# Generated by Django 6.0.3 on 2026-03-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0002_cartitem_alter_cart_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_sales', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.subscriber'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vehicle_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicletype'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_sales', to='core.employee'),
        ),
    ]
