# Generated by Django 6.0.3 on 2026-03-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0001_initial'),
        ('transactions', '0002_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expences', to='transactions.transaction'),
        ),
    ]
